
CREATE TABLE IF NOT EXISTS sys_user (
  UserId INT(11) NOT NULL AUTO_INCREMENT,
  UserName VARCHAR(45) NOT NULL,
  NickName VARCHAR(45) NOT NULL,
  Pwd VARCHAR(128) NOT NULL,
  Forbid INT(1) NOT NULL,
  Email VARCHAR(45),
  Cellphone VARCHAR(45),
  PRIMARY KEY (UserId),
  UNIQUE KEY sys_user(UserName)
) ENGINE=INNODB DEFAULT CHARSET=utf8;
